DROP TABLE IF EXISTS movie cascade ;
DROP TABLE IF EXISTS mpa cascade;
DROP TABLE IF EXISTS genre cascade;
DROP TABLE IF EXISTS genre_movie cascade;
DROP TABLE IF EXISTS app_user cascade;
DROP TABLE IF EXISTS user_friend cascade;
DROP TABLE IF EXISTS MOVIE_LIKES cascade;

CREATE TABLE IF NOT EXISTS  mpa (
    id integer generated by default as identity primary key,
    mpa_name varchar UNIQUE
);

CREATE TABLE IF NOT EXISTS movie (
    movie_id bigint generated by default as identity primary key,
    movie_name VARCHAR(255) NOT NULL,
    description VARCHAR(200) NOT NULL,
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL,
    rate INTEGER,
    mpa_id INTEGER NOT NULL REFERENCES mpa(id)
    );

CREATE TABLE IF NOT EXISTS  app_user (
    id BIGINT generated by default as identity primary key,
    email varchar NOT NULL,
    login varchar NOT NULL,
    name varchar,
    birthday date
);

CREATE TABLE IF NOT EXISTS  genre
(
    id integer generated by default as identity primary key,
    genre_name varchar
);

CREATE TABLE IF NOT EXISTS  genre_movie (
    id integer generated by default as identity primary key,
    movie_id bigint REFERENCES movie(movie_id),
    genre_id integer REFERENCES genre(id)
    );

CREATE TABLE IF NOT EXISTS  user_friend (
    user_id bigint REFERENCES app_user(id),
    friend_id bigint REFERENCES app_user(id),
    CONSTRAINT user_friend_pk primary key (user_id, friend_id)
    );

CREATE TABLE IF NOT EXISTS  movie_likes (
    movie_id bigint REFERENCES MOVIE(movie_id),
    user_id bigint REFERENCES app_user(id),
    CONSTRAINT movie_user_pk primary key (movie_id, user_id)
    );

INSERT INTO genre (genre_name)
VALUES ( 'Комедия' ), ('Драма'), ( 'Мультфильм' ), ('Триллер'),( 'Документальный' ), ('Боевик');


INSERT INTO mpa (mpa_name)
VALUES ( 'G' ), ('PG'), ( 'PG-13' ), ('R'),( 'NC-17' );

INSERT INTO APP_USER (email, login, name, birthday)
VALUES ( 'olya@olya.ru', 'olya', 'olya', '1989-11-06' ),
       ( 'dima@olya.ru', 'dima', 'dima', '1990-01-01' ),
       ( 'sasha@olya.ru', 'sasha', 'sasha', '2019-09-20' );

INSERT INTO MOVIE (movie_name, description, release_date, duration, rate, mpa_id)
VALUES ( 'movie', 'descr', '2016-05-05', 120, 4, 1 ),
       ( 'movie2', 'descr2', '2016-04-04', 130, 5, 2 ),
       ( 'movie3', 'descr3', '2002-04-04', 65, 1, 3 );



