DROP TABLE IF EXISTS movie cascade ;
DROP TABLE IF EXISTS mpa cascade;
DROP TABLE IF EXISTS genre cascade;
DROP TABLE IF EXISTS genre_movie cascade;
DROP TABLE IF EXISTS app_user cascade;
DROP TABLE IF EXISTS user_friend cascade;
DROP TABLE IF EXISTS MOVIE_LIKE cascade;

CREATE TABLE IF NOT EXISTS  mpa (
    id integer generated by default as identity primary key,
    mpa_name varchar UNIQUE
);

CREATE TABLE IF NOT EXISTS movie (
    movie_id INTEGER generated by default as identity primary key,
    movie_name VARCHAR(255) NOT NULL,
    description VARCHAR(200) NOT NULL,
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL,
    rate INTEGER,
    mpa_id INTEGER NOT NULL REFERENCES mpa(id)
    );

CREATE TABLE IF NOT EXISTS  app_user (
    id integer generated by default as identity primary key,
    email varchar NOT NULL,
    login varchar NOT NULL,
    name varchar,
    birthday date
);

CREATE TABLE IF NOT EXISTS  genre
(
    id integer generated by default as identity primary key,
    genre_name varchar
);

CREATE TABLE IF NOT EXISTS  genre_movie (
    id integer generated by default as identity primary key,
    movie_id integer REFERENCES movie(movie_id),
    genre_id integer REFERENCES genre(id)
    );

CREATE TABLE IF NOT EXISTS  user_friend (
    user_id integer REFERENCES app_user(id),
    friend_id integer REFERENCES app_user(id),
    CONSTRAINT user_friend_pk primary key (user_id, friend_id)
    );

CREATE TABLE IF NOT EXISTS  movie_likes (
    movie_id integer REFERENCES MOVIE(movie_id),
    user_id integer REFERENCES app_user(id),
    CONSTRAINT movie_user_pk primary key (movie_id, user_id)
    );

INSERT INTO genre (genre_name)
VALUES ( 'Комедия' ), ('Драма'), ( 'Мультфильм' ), ('Триллер'),( 'Документальный' ), ('Боевик');

INSERT INTO mpa (mpa_name)
VALUES ( 'G' ), ('PG'), ( 'PG-13' ), ('R'),( 'NC-17' );